-- ALTER SEQUENCE roles_id_seq RESTART WITH 1;

TRUNCATE TABLE public.users, public.posts, public.images, public.comments, public.types, public.roles, public.cities, public.categories RESTART IDENTITY CASCADE;

INSERT INTO public.roles (nombre) VALUES
	('admin'),
	('usuario');

INSERT INTO public.types (name,slug,description,image,active) VALUES
	('Productos','productos','','',true),
	('Servicios','servicios','','',true),
	('Turismo','turismo','','',true),
	('Inmuebles','inmuebles','','',true);

INSERT INTO public.categories (name, slug, description, image, active) VALUES
	('Medicina y Salud', 'medicina-y-salud', '', NULL, true),
	('Ropa y Moda', 'ropa-y-moda', '', NULL, true),
	('Alimentos y Bebidas', 'alimentos-y-bebidas', '', NULL, true),
	('Tecnología y Electrónica', 'tecnologia-y-electronica', '', NULL, true),
	('Hogar y Decoración', 'hogar-y-decoracion', '', NULL, true),
	('Automotriz', 'automotriz', '', NULL, true),
	('Belleza y Ciudado Personal', 'belleza-y-cuidado-personal', '', NULL, true),
	('Entretenimiento y Cultura', 'entretenimiento-y-cultura', '', NULL, true),
	('Deportes', 'deportes', '', NULL, true),
	('Servicios Financieros', 'servicios-financieros', '', NULL, true),
	('Compra y Venta', 'compra-y-venta', '', NULL, true),
	('Arrendamiento', 'arrendamiento', '', NULL, true),
	('Construcción', 'construccion', '', NULL, true),
	('Hotelería', 'hoteleria', 'Hoteles, hostales, arrendamiento de habitaciones, casas, apartamento y fincas por horas, días, semanas y meses.', NULL, true),
	('Educación', 'educacion', 'Centros educativos, institutos de idiomas, cursos de cualquier tipo.', NULL, true),
	('Restaurantes', 'restaurantes', '', NULL, true),
	('Cafés ', 'cafes', '', NULL, true),
	('Barberías y Estilistas', 'barberias-estilistas', '', NULL, true),
	('Mascotas', 'mascotas', '', NULL, true),
	('Bolsa de empleo', 'bolsa-de-empleo', '', NULL, true),
	('Servicios de atención ciudadana', 'servicios-de-atencion-ciudadana', '', NULL, true);

INSERT INTO public.cities (name, slug, description, image, active) VALUES
	('Armenia', 'armenia', NULL, NULL, true),
	('Buenavista', 'buenavista', NULL, NULL, true),
	('Calarcá', 'calarca', NULL, NULL, true),
	('Circasia', 'circasia', NULL, NULL, true),
	('Córdoba', 'cordoba', NULL, NULL, true),
	('Filandia', 'filandia', NULL, NULL, true),
	('Génova', 'genova', NULL, NULL, true),
	('Montenegro', 'montenegro', NULL, NULL, true),
	('Pijao', 'pijao', NULL, NULL, true),
	('Quimbaya', 'quimbaya', NULL, NULL, true),
	('Salento', 'salento', NULL, NULL, true),
	('Tebaida', 'tebaida', NULL, NULL, true);

INSERT INTO public.users (name, email, password, remember_token, role_id) VALUES
	('Administrador', 'miquindio2024@gmail.com', '$2y$12$n3/Luf7MRXASbpcyjQCV3.Ozq.F/mKQ4b.lGUhOO2z8xE3WYfUHYC', NULL, 1),
	('Jorge Iván Quintero', 'ingenierojorgeivanquintero@gmail.com', '$2y$12$O7DpLzOiSaEyyZPkm2boB.q5Kdgr4U8tm4XMDsxHhwehoeiYD2xou', NULL, 2),
	('Gloria Agudelo', 'agudelocalderong@gmail.com', '$2y$12$g7/jU/vrizasybr86xuQNuIz/Dq2HKlDoM2syAqL1waJWbXaQOtIO', NULL, 2),
	('Carlitos', 'tecnomundo_2008@hotmail.com', '$2y$12$dRkELQrR6eA.I129npzVe.LVMREpZnBM9HB10lVmZk0bobgZgW2i2', NULL, 2),
	('Santiago Blandon', 'santiblandon2020@gmail.com', '$2y$12$4Ad91p0CWkK3MdL5gtHff.dEbrknJ7q74P3vimq6FlN94aSZ47vqy', NULL, 2),
	('Dana', 'car1087@hotmail.com', '$2y$12$DpYfDt/rcrvX26H9HX55vuYGyrKQn68OMDv2zzf02NXLJhrLYjdlG', NULL, 2),
	('Danna444', 'danna55892@hotmail.com', '$2y$12$2nT/1M2YsWK6qDAJkxlV4e.YW/yZJRZiAwvb6ZxvA2g2twdWJcctO', NULL, 2),
	('Mara henao', 'danna78@gmail.com', '$2y$12$0ivXOrL7mJQBxpc35o6oEuoPhiW79iiZifaJMoY/N2/teSBSb0F/.', NULL, 2),
	('luisa', 'luisafernandaperezaguirre@gmail.com', '$2y$12$zc7wWhzrcTbfbIKQzPJsUO1pYggI7EPUMr4QewTSZM3c/p.MYOVSW', NULL, 2),
	('Jhon freddy', 'jhon.m.o@hotmail.com', '$2y$12$Vh.fMKcM5kdM5kl3DtfxRO0Ro5Po8KJah0KXCSjIdMT2rs1MF1OTW', NULL, 2),
	('Jenniffer toro granada', 'jennitorogranada28@gmail.com', '$2y$12$NlykLYpIFAuyC3up8bhBt.t.2UV7HcWButgQkY7XLdxERHWDkEvvW', NULL, 2),
	('Yesica Paola Salamanca', 'yepasa96@gmail.com', '$2y$12$STQw0PtIBezO6XK.VE.RMeKHENtm5VfRuEDi6hcOBZ9N0O5cW8j1K', NULL, 2),
	('Edgar Rincon', 'edgarrinconl@gmail.com', '$2y$12$1ncIvpfzpUQNS7b0GJi8..c/4a2Px.G3zdaMAfxYlwEd6NNcfOs/K', NULL, 2),
	('Erika Patricia Jurado Villamil', 'epjuradov@gmail.com', '$2y$12$Cf5xrC0L9ozbocJZfalBj.y9CQ9.yuGdk.j2bLhDNxB4R9E6ITiN2', NULL, 2),
	('Paola carvajal', 'valentina2017camila@gmail.com', '$2y$12$idxMntvDSIbBvNE308WES.YP5DHKXWGkH2PPp0p6A0ew1j4N21d0O', NULL, 2),
	('Aura María Valencia', 'kaffalaaldea@gmail.com', '$2y$12$eHNWJosceAMSfG5fTuZvTu0Cs2geiMqy.dSsQRaFT/OUDzNhpBBE2', NULL, 2),
	('Jenniffer Toro granada', 'musareposteria24@gmail.com', '$2y$12$vQTac.Rb.mEIpoMdXXZCluvNZqsDhb1xdm939qGtaiVsOpxpxMQtm', NULL, 2),
	('Jennifer Lorena Osorio Martínez', 'jenniosorio26@hotmail.com', '$2y$12$0RVcnuBJ0tTVlGh7smaU/OsJJTwiOfiOxN0plX94Dhmv.dHE9XF4e', NULL, 2),
	('Lina maria espinosa', 'lina.emiliana@gmail.com', '$2y$12$0BtHEIKx1AtfuV3tUG0nqu9euMsiGoljPKycwbGVuBIkiQb08BIhy', NULL, 2),
	('Yahira Guzmán', 'yahiguz@gmail.com', '$2y$12$/CIsT4KBp91/P64nLHN5WuIkF4Z2.Ey3.NT7B9FxHDQWmINWycY32', NULL, 2),
	('Cristina Garci', 'aucrisga@hotmail.com', '$2y$12$6FNAee/pEuh4nNycDERrw.VA.5t9rfS8.C3dXYc2mUOr1Q0UuLeza', NULL, 2),
	('Jessika García Villamil', 'jessica.garciag@cun.edu.co', '$2y$12$dQkSoLRx9SRY4faZx5.M/ubTKw12sBpkepNHiZLHnW.aVp8F0KAG6', NULL, 2),
	('Patricia Amaya', 'grecacafebar@gmail.com', '$2y$12$X3COPi/MvR0AbeK97iyQdeCqEFc8gbmSjJGE.a8/TcX9DoX85q86K', NULL, 2),
	('Carlos Grajales', 'carloshernangrajalestinoco@gmail.com', '$2y$12$.UzoBldYBmGXDMBhtdnWc.SDZPmg84/Et//.EBP39KOa0gOZdshDO', NULL, 2),
	('Edelmira', 'edelmirachimuelo@gmail.com', '$2y$12$65UsbX7YiJhiaYYAPjlZ9ODsJYDIMTw3iyHwrwcmVtAHk7b8cUOmy', NULL, 2),
	('Sandra Rincón', 'srincon072@gmail.com', '$2y$12$BRvGqMVZq4JGuQj8Zy7EluPW6yulJH8z/38bgFv6FqJg0X/w4xu9a', NULL, 2),
	('Sandra García', 'sandramilena162@hotmail.com', '$2y$12$eIIVPkA15.IL5ZZjLYGEHeXseZkVGpMb/ZQe4ZvLY6AfEITThustC', NULL, 2),
	('Mariana Gómez Hernández', 'mariaagh@gmail.com', '$2y$12$UDMbnCEbS7P4izXafSJ0mOl6EIh1UBWQYK0yXIKEyA/pwifPKawSm', NULL, 2),
	('jorge', 'bremenlapasioncafe2020@hotmail.com', '$2y$12$abJlaVZhdSN.agK1N4qKYuMdQZpAOfUJyaWw8ehT4EJ.iDyYOEMl6', NULL, 2),
	('María Daniela Muñoz Cardona', 'danilaura99@hotmail.com', '$2y$12$p5eGL9sfT9p9mPvzJnU.fOL5mHCQJkLDj9vBm8sJPkNOdTH/fogyO', NULL, 2),
	('Lily', 'lilyrepresentanteventas@gmail.com', '$2y$12$AaqpwSib90FKRZBZsUvUG.R71ewXDE0RcW6zSf48Yf2In3pd2y.Uq', NULL, 2),
	('Yamilet', 'yamilemontes899@gmail.com', '$2y$12$Rib7qy10zHJoUYaLMFy01uHnR/xxfppgu963XImMx9G6WgupWulGa', NULL, 2),
	('Jose González', 'joseoctaviogonzalez1997@gmail.com', '$2y$12$JXNCBy6BgROksABcTVKSU.jEqTHoJrvtbwVdBBFNFgK9gEx3lGYNW', NULL, 2),
	('Valentina', 'gallegomarinv@gmail.com', '$2y$12$IfBc/5fsU7Dxdq7N086qE.UmUyEw9WxteIcl7h1Nu3dgcYPyDe/Tu', NULL, 2),
	('Alexander orozco', 'tataslolis@gmail.com', '$2y$12$kZgqlTzGsWRedU0aySofRu9rJcBgbSpQHZveyFMrOJtpjZQQwAJUi', NULL, 2),
	('yuli marcela mejia orozco', 'creartey.v@gmail.com', '$2y$12$Azo6STdCQDAiX1Xf0ds7Nesnv7XDwZ4soYHOclCD1ZKFTuaeoKmGa', NULL, 2),
	('Angie Paola', 'saldanarivangie@miugca.edu.co', '$2y$12$2HOBL0hfim40dP1f9AzJq.29N/iUWWOObj0Oujgm3I5L9laD5HkoO', NULL, 2),
	('compucell circasia', 'compucellcir@gmail.com', '$2y$12$3FKlH8tlC2dr3UwPcucAqeGH.jbR0WbTpp3jWPUHbICC.WaOQlQz.', NULL, 2),
	('Luz amparo días', 'gallardoamparo87@gmail.com', '$2y$12$CeRJ1Tje0zW5uzJsH3dfheqUyK7HM/W..y2hj293XgL.lZVQyxFA.', NULL, 2),
	('La cascada', 'lacascadacafee@gmail.com', '$2y$12$U.t5zG.r/TEyQy3wAOxn.OnufkCPTXqGpHaUAGZHcM71xGLxSjLl2', NULL, 2),
	('La Ruana Calarcá', 'laruanacalarca1220@gmail.com', '$2y$12$pDvDzdRwrNq.PT0v0XTMtO25dRP9uQs0aFRnZiBguZQGfDYqo1rFO', NULL, 2),
	('Lina maría', 'victoria2019martinez@gmail.com', '$2y$12$eJbq.LivLofEWvctSlPv7u1wbHNH6CDid3bJqqA0vVJmu8pQNyGem', NULL, 2),
	('ZH CUEROS', 'cueroszh@gmail.com', '$2y$12$Tp0FJsEZklhTreooi24vVeHkUPj3qNg8qiuzwW3zesSUL6uj2S3I.', NULL, 2),
	('Luz amparo Días Gallardo', 'arepas@123', '$2y$12$jcxhrYRqaMwSytwci8NtNehH6tPlOiTPnSGymkW/RXNwNVoGjk0NK', NULL, 2),
	('Jorge', 'bremenlapasioncafe000@gmail.com', '$2y$12$6yQ8sCqIVjFC.g/rP66hLe4ZrnnkyOa0tIDGII2jsV90O2Kpqcg2m', NULL, 2),
	('Malli Daniela Agudelo', 'malliagudelo113@gmail.com', '$2y$12$QKUmTdKKlFx9d7cJXCoE4.VcmBNofjAbuuKQIA5kstZfhKOsbAeuO', NULL, 2),
	('Marcela Cardona', 'fitlifeshop1412@gmail.com', '$2y$12$z0msBKyXlIOpp0KjXnAnsef7sLWrmmJmkq9TBO2cYA.LHWcXZRPim', NULL, 2),
	('Oscar Duvan', 'oscarduvansoto@gmail.com', '$2y$12$c2uZtzXBpFD/RYHUoE9GWOPk68G1T6cniukD69GkPihY3TbMR2u7a', NULL, 2),
	('Yuri', 'yuryvivianamarin@gmail.com', '$2y$12$1WXNajhXIvVs./GbSi6x3eYv.x69mOxNUp6Pde8dX3ch7Nmqz1bjG', NULL, 2),
	('Alejandra Muñoz Salazar', 'floristeriaydetallescircasia@gmail.com', '$2y$12$RdDAeNdEGIMQlqyie6VXle5n2iu4r7FOJBEeEI7IDWEEpseqhv8eS', NULL, 2),
	('Alejo', 'alejandro_agudelo_11@hotmail.com', '$2y$12$wZBPojwx74os/T24rPcKWO4HdsD15HYtE/ooaoTo5FEeWU3WAEX/m', NULL, 2),
	('AGUEDA VELANDIA', 'avelandiavega1970@gmail.com', '$2y$12$vQyQ3dcy2xR7Sw5VyvDzKebox2yRdtsB4Y/o92OqpsjvlpWh/ts1u', NULL, 2),
	('Jhoany Ledesma', 'ledesmajhoany713@gmail.com', '$2y$12$rxP9Gb7e4//G.nI2aWIuAeCw44gQAViFkNdoAGpXAfWW6Ei.VayK.', NULL, 2),
	('Diana', 'diana.ishabel1018@gmail.com', '$2y$12$VTGaU34zE1m.IdpCL0lDSe17PSHX5ygxwRyVgWYdqAfegtkpdq9VK', NULL, 2),
	('Olma lucia', 'delavegasabrosa@gmail.com', '$2y$12$CX.IQSDK/3NZMbE4pB3h..uG/84mrLiWmS3p6N89L7iZSeKMVHCa2', NULL, 2),
	('Fraiche', 'fraichecaicedonia@gmail.com', '$2y$12$tY7ldVXtFbiUL8Q4zejwnueynh2X2u2PCwG3UvFA1.LQ/3jCTq/Na', NULL, 2),
	('Juan David', 'motatoj60@gmail.com', '$2y$12$vOLOYKAdi0xKEDb8TMYIOe1fD.qHrAaAoNazPhHISX57RbXiM19DW', NULL, 2),
	('Andrez Gutierrez', 'and.rez.15dc@gmail.com', '$2y$12$EJOw0oD3DTK3mHzLJM9zVuoQJh5mcU4HCnf9IOXfjplerCIgaGTiG', NULL, 2),
	('Lina Ayala', 'ablinamaria@gmail.com', '$2y$12$b/dsunyLk7.zBhujmalNRuPpdXGHldOAlzHwErP0Gn5q.JUqWRwtm', NULL, 2),
	('Miss papa', 'alejita-1498@hotmail.com', '$2y$12$1rEtBxqkKGCiCVSozX.Ah.4y6YtGkXsknmM1z8zz1yTwiRR3cgGNG', NULL, 2),
	('Yolibeth', 'yolibethvides792@gmail.com', '$2y$12$D4gtkpztUgw87z2KcesFb.RJr2i1jxWeTn9.qoqcFKmavlMagMkUS', NULL, 2),
	('Travesias Restaurante', 'travesiasrestauranteparrilla@gmail.com', '$2y$12$u7s6zwmJYYr9QCJqi.F6A.BZCIxleXmEYu.0Lkpb2VMTflOn98oge', NULL, 2),
	('Miss papa', 'mhurtadoagudelo@gmail.com', '$2y$12$yQZRGYzeTX8VWTI1faG1KOBEdm4KkCeOojDDpJFlWdS0eCZusWdsO', NULL, 2),
	('Juliana', 'isabellaforero@gmailcom', '$2y$12$1szPqOB/y7DTdsHfNHw.LukamH2YD5uKJ6vyhLA7CZzB1tpERm896', NULL, 2),
	('Agropecuaria samy', 'jaimesolocarnes@gmail.com', '$2y$12$PfCdxeSRCTAJCtxHC7lIQ.wwWt3xz94epL0gPvHzPbikE.JLlG9wW', NULL, 2),
	('Yuli Paulin', 'jjxd64@gmail.com', '$2y$12$z7QzyXWdVRSlOQjlpDimSu6cgJyviYmxCohQu3Kqf2Q4UrqbCAFNu', NULL, 2),
	('Siempre Alegre Market', 'samarketcircasia@gmail.com', '$2y$12$SkOyXvQsolQ72SLFi6Hw/OYiwff6nW5MWatLpZQe6.FNXfl5Xf0bG', NULL, 2);

INSERT INTO public.posts (user_id, city_id, category_id, type_id, title, slug, description, visits, likes, phone, address, delivery, facebook, instagram, rooms, baths, area, price, published, location, active) VALUES
	(2, 9, 1, 2, 'Consultorio Mishelle Montoya', 'consultorio-mishelle-montoya', 'Nos especializamos en ofrecer atención dental integral con los más altos estándares de calidad. Con un equipo de profesionales dedicados, te aseguramos una experiencia cómoda y satisfactoria. ¡Ven y descubre cómo podemos mejorar tu sonrisa', 1, 0, '3113321524', 'calle 6 numero 13-57', true, '1', '1', NULL, NULL, NULL, NULL, '2025-09-01', NULL, true),
	(2, 4, 3, 1, 'Carnes Mickey', 'carnes-mickey', 'Encontrarás la mejor carne con el sabor más delicioso a un precio justo. Ofrecemos platos ejecutivos y a la carta. Ven y conoce nuestro espectacular menú que te dejará encantado', 0, 0, '3113385152', 'Calle 7 # 14-41', false, 'https://www.facebook.com/profile.php?id=100063489911771&mibextid=ZbWKwL', '1', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/HeWW6ViEBAmKmtik7', false),
	(2, 1, 2, 1, 'Detallitos Fashion', 'detallitos-fashion', 'Detallitos Fashion es una tienda especializada en accesorios de moda y productos de belleza. Nuestro enfoque es ofrecer una variedad de artículos para todas las edades, desde jóvenes hasta adultos, que buscan realzar su estilo personal con detalles únicos y de alta calidad.', 2, 0, '3113321547', 'Calle Real # 8-52', false, '1', '1', NULL, NULL, NULL, NULL, '2025-08-02', NULL, false),
	(2, 1, 3, 1, 'En Madas_Food', 'en-madas-food', 'Puedes crear tu propia comida. Deja volar tu imaginación y prepara tu plato favorito. Ofrecemos hot dogs, hamburguesas, sándwiches, fresas con crema y mucho más. ¡Ven y disfruta de la experiencia!', 14, 0, '3200701192', 'Clle 6 # 13 49', false, '1', '1', NULL, NULL, NULL, NULL, '2025-08-02', '', true),
	(2, 4, 3, 1, 'Barenque', 'barenque', 'Estamos ubicados diagonal a la alcaldía. Disfruta de un delicioso café y muchos otros productos en un ambiente al aire libre muy acogedor. ¡Ven y haz tu día más cálido con una taza de nuestro exquisito café!', 10, 0, '321 5618514', 'Parque principal', false, '100091291917095', '1', NULL, NULL, NULL, NULL, '2025-08-02', '', true),
	(2, 4, 3, 1, 'La Selecta', 'la-selecta', 'Ven y disfruta de nuestro pan recién salido del horno, calientito y delicioso. Además, ofrecemos un exquisito servicio de desayunos y postres. ¡Te esperamos para brindarte la mejor atención', 6, 0, '321 5614587', 'Parque principal', false, 'tradicion.echa.calidad', '1', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/4yUuw1wAtWTUN3SQA', true),
	(2, 4, 3, 1, 'Pollo Dorado', 'pollo-dorado', 'Descubre el sabor auténtico del mejor pollo asado. Ofrecemos suculentas presas de pollo apanadas y un almuerzo delicioso que te hará volver por más. Ven y deléitate con nuestro pollo dorado, preparado con amor y los ingredientes más frescos. ¡Te esperamos para una experiencia culinaria inolvidable!', 0, 0, '3115548526', 'Carrera 15 # 16 89', false, '100063953197093', '1', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/VKJtkUFgpNgwUzxR8', false),
	(2, 1, 3, 1, 'Naranja Dulce', 'naranja-dulce', 'Vida Natural es una tienda especializada en productos naturistas, dedicados a promover la salud y el bienestar a través de alternativas naturales y ecológicas. Ofrecemos una amplia gama de productos que ayudan a mantener un estilo de vida saludable y equilibrado, desde suplementos alimenticios hasta productos de cuidado personal.', 0, 0, '3115548545', 'Carrera 15 # 8 68', false, '101870004816730', NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, false),
	(2, 4, 7, 2, 'prueba', 'belleza-integral', 'Belleza Integral es un centro de estética y spa dedicado a realzar la belleza natural de nuestros clientes y proporcionar un espacio de relajación y bienestar. Ofrecemos una amplia gama de servicios de belleza y tratamientos personalizados, utilizando productos de alta calidad y técnicas innovadoras para asegurar resultados excepcionales.', 0, 0, '3115547777', 'Carrera 15 # 14 77', false, '1', NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, false),
	(2, 4, 3, 1, 'Car', 'carnes-mi-pueblito', 'Carnicería Mi Pueblito es un establecimiento dedicado a ofrecer carne de alta calidad, con un enfoque en la frescura, la procedencia ética y el servicio personalizado. Nos especializamos en una amplia variedad de cortes de carne, asegurando que cada producto cumpla con los más altos estándares de calidad y sabor.', 2, 0, '3115547521', 'Carrera 15 # 14 83', false, '1', NULL, NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/A9gFcwHBGzeDcHy99', false),
	(2, 4, 2, 1, 'Lima Azul', 'lima-azul', 'Brillos Eternos es una joyería especializada en piezas de fantasía y acero inoxidable, diseñadas para aportar elegancia y estilo a cualquier ocasión. Nos enorgullecemos de ofrecer una colección diversa y asequible de joyas, que incluyen desde los clásicos atemporales hasta las tendencias más modernas.', 8, 0, '3115546325', 'Carrera 15 # 14 78', false, '1', NULL, NULL, NULL, NULL, NULL, '2025-08-02', '', true),
	(2, 4, 11, 2, 'Venta', 'impresiones-3d', 'se vende bicicleta para niño, muy buenas condiciones muy poco uso con un hermoso color rojo por tan solo 280,000 pesos', 0, 0, '3113317247', 'Calle 8 número 16 55', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/H7nifqB1pBBLDNqLA?g_st=com.google.maps.preview.copy', false),
	(2, 1, 4, 2, 'Tecnopolis', 'tecnopolis', 'Todo en tecnología', 0, 0, '3121212121', 'Av Bolívar 12-04', true, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, false),
	(2, 1, 4, 2, 'Fundación Genios', 'fundacion-genios', 'Les abrimos muchas ventanas, donde se asoman, conocen, aprenden, y desarrollan todo su potencial, creatividad e ingenio.', 16, 0, '3206805180', 'Calle 1 Norte # 16-69', false, 'facebook.com/geniosfundacion', 'https://instagram.com/fundaciongenios', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/3xxQdnPfLpcSFAGS8', true),
	(2, 4, 11, 1, 'Venta de bicicleta para niño', 'todo-en-deportes', 'Vendo hermosa bicicleta roja en excelentes condiciones, con muy poco uso. Ideal para niño de 5 a 8 años. Precio: 280 mil pesos.', 13, 0, '3113317247', 'Calle 8 16 33', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/H7nifqB1pBBLDNqLA?g_st=com.google.maps.preview.copy', false),
	(3, 4, 11, 1, 'venta de celular Samsung Galaxy A22', 'venda-de-celular-samsung-galaxy-a22', 'Se vende Samsung Galaxy A22 en excelente estado.\r\nEl teléfono ha sido bien cuidado y está completamente funcional. Se ha realizado un cambio de pantalla recientemente, por lo que la pantalla luce impecable. El vidrio de la cámara trasera tiene algunas pequeñas grietas estéticas, pero la cámara sigue funcionando perfectamente.\r\n\r\nPrecio: $220.000', 4, 0, '3160438118', 'calle 8 numero 16 55', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, false),
	(4, 4, 3, 2, 'Summer cafe prueba', 'summer-cafe-prueba', 'Encuentra todo aquí de cafes especiales y comida rica', 0, 0, '3226543218', 'Plaza principal al frente de la iglesia', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, false),
	(6, 4, 14, 3, 'Hotel Vivienda Turística', 'hotel-vivienda-turistica', 'Vivienda Turística Como Mi Hogar Hotel en Circasia Quindio , comodas Habitaciones, baño privado agua caliente, wifi,tv,ventilador,espacios sociales, muy cerca del parque principal.\r\nCircasia es el Municipio con mejor Ubicación Geográfica , todos los sitios de interes muy cerca.', 14, 0, '3122278937', 'Carrera 17 # 4 -22', false, 'https://www.facebook.com/jhon.morales.923519?mibextid=ZbWKwL', 'https://www.instagram.com/viviendaturisticacomomihogar/profilecard/?igsh=Z3FzaGcydHRjODQx', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/D6ah37gTfsywLJMU7?g_st=com.google.maps.preview.copy', true),
	(2, 2, 2, 2, 'Ropa fina buenavista', 'ropa-fina-buenavista', 'Ropa fina Buenavista', 0, 0, '5545454', 'Plaza de Bolívar', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, false),
	(5, 4, 5, 1, 'Quindiaroma', 'quindiaroma', 'Aromas de alta calidad para todo tipo de espacios locales comerciales oficinas y hogar ventas al por mayor y al detal.', 21, 0, '3133258646', 'Circasia Quindío', true, 'https://www.facebook.com/share/1D9HWW2fgN/', 'https://www.instagram.com/quindiaroma/profilecard/?igsh=MXc4bGg4YjBpNHF2dg==', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/PCRoY18EGYPNR7RC7', true),
	(7, 4, 3, 1, 'Musa repostería', 'musa-reposteria', '', 0, 0, '+573233126360', 'Calle 6 #10-38', true, NULL, NULL, NULL, NULL, NULL, NULL, '2025-09-01', 'https://maps.app.goo.gl/MyRKZsQMfegLbYjM8?g_st=com.google.maps.preview.copy', false),
	(8, 4, 3, 1, 'The Empanadas Crispy', 'the-empanadas-crispy', 'Tenemos para ti una receta mágica en nuestras empanadas, ven y disfruta de su sabor y acompañalas con unas ricas salsas y ají al natural. \r\nEmpanadas de:\r\n* Carne\r\n* Pollo\r\n* Mixta\r\n* Alechonada\r\n* Hawaiana \r\n* Queso \r\n* Queso bocadillo', 17, 0, '3228600654', 'Cra 16 #3-57', true, 'https://www.facebook.com/profile.php?id=61556274299293&mibextid=ZbWKwL', 'https://www.instagram.com/theempanadascrispy?igsh=NHRpNmpxM3FoNW5l', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/XT7ncoCy7hE3PGJj9', true),
	(9, 4, 5, 1, 'Dulce Regalo', 'dulce-regalo', 'Rosas, peluche y chocolates, el detalle perfecto para enamorar a una mujer 💘\r\nTe asesoramos y damos ideas personalizadas para tus fechas especiales, que esperas para contactarte con nosotros?', 10, 0, '3145914653', 'Cr12N*7-18', true, 'https://www.facebook.com/eldulceregalo2/?locale=es_LA', 'https://www.instagram.com/dulceregalo.arm?igsh=MWVpMnQxdXM0dGhqNg==', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/UJDbx9sHsvn71Eei7?g_st=com.google.maps.preview.copy', true),
	(10, 4, 17, 1, 'Kaffa La Aldea', 'kaffa-la-aldea', 'Tienda de café en donde se disfruta de una buena taza ☕️ de origen… aquí donde se disfruta de la calma y tranquilidad con amigos, con familia ó a solas. Un buen lugar para relajarse y pasar una tarde tranquila. Además aquí puedes celebrar todo tipo de eventos y fechas especiales. En Kaffa La Aldea contamos con gran variedad de bebidas, tartas, pasteles, comidas rápidas. \r\nEstamos ubicados en Circasia\r\nQuindío, carrera 15 # 3-46, a dos cuadras y media del parque principal.\r\nBIENVENIDOS', 9, 0, '3113151012', 'Kra 15 No 3-46', false, 'https://www.facebook.com/share/1AduNVJ5o3/?mibextid=LQQJ4d', 'https://www.instagram.com/kaffa.laaldea/profilecard/?igsh=MW92N3R3eXowaDUybQ==', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/ddgai8MGubXqBjDX7?g_st=com.google.maps.preview.copy', true),
	(11, 4, 3, 2, 'Musa Reposteria', 'bicicleta', 'Reposteria personalizada\r\n🎂Tortas personalizadas\r\n🍮Postres\r\n🧁Cupcakes\r\n🍪 Galletas\r\n☕ Café\r\n🍹 Granizados', 2, 0, '3233126360', 'calle 6 # 10-38 Br San José', true, 'https://www.facebook.com/musareposteriaaxm', 'https://www.instagram.com/musareposteriaaxm/', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/1Thy6aAdsf8FEBB79', true),
	(12, 4, 2, 2, 'Guacaticos', 'guacaticos', 'Comercializamos accesorios y productos con motivo de aguacate. Además diseñamos y creamos en bisutería, artesanías y manualidades. Plasmando el amor por el aguacate.', 11, 0, '3042899088', 'Carrera 13 #7-20, piso 1', false, 'https://www.facebook.com/share/14ou8A9oT6/', 'https://www.instagram.com/guacaticoos/profilecard/?igsh=MTlrZTRxZmU0d3RlNA==', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/xD3jj1wFzdy3zjVs9', true),
	(13, 4, 2, 2, 'Boutique talu', 'boutique-talu', 'Es un almacén de ropa moderna y elegante, especializado en ofrecer las últimas tendencias para dama y caballero. Con una amplia variedad de prendas que incluyen desde ropa casual hasta opciones más formales, el lugar se destaca por su estilo versátil, pensada para aquellos que buscan actualizar su guardarropa con piezas de calidad y diseño contemporáneo. Ideal para quienes desean vestir a la moda, sin sacrificar comodidad ni estilo.', 8, 0, '3136174128', 'Calle 7# 12-54', true, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/AQ7qcyTDcocKo61s9', true),
	(14, 4, 9, 2, 'Almacén de bicicletas sport bici', 'almacen-de-bicicletas-sport-bici', 'Taller especializado y venta de bicicletas, repuestos y todo lo relacionado con la bici', 7, 0, '3163073935', 'Crra 13 #6-20', false, 'https://www.facebook.com/SportBiciCircasia/?locale=es_LA', NULL, NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/dPj3hj9mV8BvC1dBA?g_st=com.google.maps.preview.copy', true),
	(15, 1, 1, 2, 'Dra Cristina García G • Odontología Integral y Especializada', 'dra-cristina-garcia-g-odontologia-integral-y-especializada', 'Hola soy la Dra Cris, y ofrezco todos los servicios relacionados con odontología general y especializada. Limpiezas, Calzas, Cirugías, Coronas, Prótesis.\r\n\r\nAgenda tu cita de Valoración 📱 3104031531', 23, 0, '3104031531', 'Medicentro Alcázar Cra 13 # 3 N - 50 consultorio 808', false, 'https://www.facebook.com/dra.cristina.garcia.g?mibextid=LQQJ4d', 'https://www.instagram.com/dra.cristinagarciag/profilecard/?igsh=M2psdmN3NHcwNndw', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/gLNz6pm9hqNKT8mj8?g_st=com.google.maps.preview.copy', true),
	(22, 4, 7, 2, 'Maquillaje', 'maquillaje', 'Ven y aprovecha nuestros servicios de maquillaje para toda ocasión .', 23, 0, '3233199688', 'Calle 7 número 14-77', true, 'https://www.facebook.com/share/1Azf11HCdF/?mibextid=kFxxJD', 'https://www.instagram.com/jessika.studiodebelleza/profilecard/?igsh=MTlzaGppMTg4NGt0eA==', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/CwvmNgxHv6sF6E2KA?g_st=ic', true),
	(16, 4, 17, 1, 'La Greca Cafe Bar', 'la-greca-cafe-bar', 'Ven y disfruta de la música de los 80 y 90 acompañado de un rico café☕️ , coctel🥃,licor🥂🍻,🍷🍹granizados y otras bebidas....🍾🥃', 9, 0, '3246627456', 'Calle 8 con carrera 15 esquina local 4', false, 'https://www.facebook.com/lagreca.540485?mibextid=ZbWKwL', 'https://www.instagram.com/lagrecacafebar2024/profilecard/?igsh=MTB1dzgyaGE0dG9sOA==', NULL, NULL, NULL, NULL, '2025-08-02', 'Circasia, Quindío calle 8 carrera 15 esquina local 4', true),
	(17, 4, 1, 2, 'Ópticas Tinoco', 'opticas-tinoco', 'Ver bien para vivir mejor.\r\n20 años de experiencia en Ópticas al servicio de los Quindianos.\r\nExamen Visual Computarizado.\r\nMonturas y lentes con garantía. 🤓🌞😎', 9, 0, '3234728721', 'Calle 7 # 12 - 42', false, 'https://www.facebook.com/sandra.grajales.50309?mibextid=ZbWKwL', 'https://www.instagram.com/opticastinoco?igsh=MWI4cjhrczBwNTE0ag==', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/rkb6mkgU7aqvjmpL6', true),
	(18, 4, 5, 1, 'El Baúl De Chimuelo', 'el-baul-de-chimuelo', 'Todo para renovar y decorar tu hogar. Colchones,base cama, cobijas,vajillas hornos,extractor de jugos 🦇😊', 4, 0, '3234478259', 'Calle 7 # 10-69 local 3 baúl de Chimuelo', false, 'https://www.facebook.com/edelmirabauldechimuelo?mibextid=ZbWKwL', 'https://www.instagram.com/bauldechimuelo?igsh=NGd2Zjd6YzYxYXIz', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/y1wyqNCRkzqUneob7', true),
	(2, 8, 8, 3, 'Parque del Café', 'parque-del-cafe', 'El Parque del Café, ubicado en el Quindío, es un lugar único donde la tradición cafetera colombiana cobra vida. Disfruta de emocionantes atracciones, aprende sobre el proceso del café y explora su exuberante naturaleza. Con juegos mecánicos, espectáculos en vivo, senderos ecológicos y una deliciosa oferta gastronómica, este parque es el destino perfecto para disfrutar en familia y sumergirse en la magia del Eje Cafetero.\r\n\"Indícanos que nos encontraste en miquindio.com y te contaremos sobre nuestras promociones exclusivas.\"', 14, 0, '3232385565', NULL, false, 'https://www.messenger.com/login.php?next=https%3A%2F%2Fwww.messenger.com%2Ft%2F1428677004071648%2F%3Fmessaging_source%3Dsource%253Apages%253Amessage_shortlink%26source_id%3D1441792%26recurring_notification%3D0', 'https://www.instagram.com/parquedelcafeoficial/?igshid=YmMyMTA2M2Y%3D#', NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(2, 10, 8, 3, 'Panaca', 'panaca', 'Panaca es un parque temático único en Colombia, ubicado en el corazón del Eje Cafetero, donde la naturaleza y los animales se encuentran en un ambiente lleno de diversión y aprendizaje. Conocido por su enfoque en la vida rural y el mundo de la agricultura, Panaca ofrece una experiencia interactiva con más de 4,000 animales de diversas especies. Los visitantes pueden disfrutar de shows en vivo, recorrer senderos ecológicos, participar en actividades agropecuarias y conocer de cerca la vida en el campo. Un lugar ideal para toda la familia, donde el contacto con la naturaleza y los animales crea recuerdos inolvidables.\r\n\"Cuéntanos que nos encontraste en miquindio.com y te informaremos sobre nuestras promociones especiales en Panaca.\"', 4, 0, '3106818818', 'Km 7 Vereda Kerman, Quimbaya, Quindío', false, 'https://www.facebook.com/ParquePanaca/?locale=es_LA', 'https://www.instagram.com/panacaparque/?hl=es', NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(2, 3, 8, 3, 'JardinBotanicoQuindio', 'jardinbotanicoquindio', 'Comienza ahora\r\nSi quieres visitar físicamente nuestra sede principal en Calarcá vivirás una experiencia inolvidable. El Jardín te espera.\r\n\r\nHaz tu contribución para ingresar.\r\nTenemos nuestras alas abiertas todos los días de 8:30 am hasta las 3:30pm jornada continua, festivos también\r\n\"Cuéntanos que nos encontraste en miquindio.com y te informaremos sobre nuestras promociones especiales en Panaca.\"', 5, 0, '3104045223', 'Km 3 vía al Valle del Cauca, Calarcá, Quindío', false, 'https://www.facebook.com/JardinBotanicoQuindio/?_rdc=1&_rdr', 'https://www.instagram.com/jardinbotanicoquindio/', NULL, NULL, NULL, NULL, '2025-08-02', 'https://www.google.com/maps/place/Jard%C3%ADn+Bot%C3%A1nico+Del+Quind%C3%ADo/@4.5116806,-75.6535575,17z/data=!4m6!3m5!1s0x8e38f43b10d6dddd:0xf97d58b928ca87fe!8m2!3d4.5116806!4d-75.6509772!16s%2Fg%2F1hc0g78px?entry=tts', true),
	(2, 4, 14, 2, 'Bahialoft', 'bahialoft', 'Bahialoft Circasia se encuentra en Circasia y ofrece alojamiento con balcón y wifi gratis.', 6, 0, 'np', 'calle 7 entrada principal de circasia', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', 'https://www.booking.com/hotel/co/bahialoft-circasia.es.html?label=circasia-IQ6LUvJJt77fo5KFsBiJkgS525510336165%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atikwd-469784284959%3Alp21519%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9YdnZzv7u3SiOco5fpqS0M1M&sid=d72319a879dd8f5aa5b395e593cfca6b&gclid=EAIaIQobChMIkqLBuLTsiQMVlYJaBR0kHyTGEAAYASAAEgJryvD_BwE&aid=306396&ucfs=1&arphpl=1&dest_id=-580961&dest_type=city&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=1&hapos=1&sr_order=popularity&srpvid=cd7f138e9fa80256&srepoch=1732157355&from=searchresults#map_opened-hotel_sidebar_static_map_capla', true),
	(2, 1, 8, 3, 'Parque De La Vida', 'parque-de-la-vida', 'Así que usted está de visita en Armenia y tiene unas cuantas horas libres para hacer algo, pero no son los suficientes como para una salida fuera de la ciudad. No hay problema, ahí es cuando el plan puede ser una visita a un muy buen parque de la ciudad: El Parque de la Vida de Armenia.\r\n\r\nY no es un parque cualquiera, es un parque muy especial y muy buen cuidado al cual se puede llegar fácilmente.\r\n\r\nEl Parque de la Vida de Armenia es uno de los más grandes pulmones verdes de la capital Quindiana. Con una superficie total de más o menos 8 hectáreas, este espacio eco-turístico sirve a los habitantes de la ciudad como paraíso en medio del concreto y caos de la vida diaria.\r\n\"Cuéntanos que nos encontraste en miquindio.com y te informaremos sobre nuestras promociones especiales.', 1, 0, '3215594617', 'Avenida Bolívar, calle 6 Norte, Armenia', false, 'https://www.facebook.com/parquedelavidaarmeniaquindiocolombia/?locale=es_LA', 'https://www.instagram.com/parquedelavida/', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/SfirrwN82kiiVZRF9', true),
	(2, 4, 21, 2, 'Alcaldía de Circasia', 'alcaldia-de-circasia', 'Horario de atención: Lunes a Jueves: 7:30 a.m. a 12:00 p.m. y de 2:00p.m. a 6:30 p.m. Viernes: 7:30 a.m. a 12:00 p.m. y de 2:00p.m. a 5:30 p.m.', 5, 0, '+57) 6 7584024', 'Carrera 14 # 6-37', false, 'https://www.facebook.com/circasiaquindio.alcaldiamunicipal/?locale=es_LA', 'https://www.instagram.com/alcaldiadecircasia/?hl=es', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/bqRRBuJipjvWofN28', true),
	(2, 6, 8, 2, 'Alcaldía de Filandia', 'alcaldia-de-filandia', 'Horario de atención: Lunes a Viernes de 8:00Am a 12:00M y de 2:00Pm a 6:00Pm - Sábados de 8:00Am a 12:00M\r\n\r\nLínea de atención gratuita: 018000954949\r\nCorreo institucional: contactenos@filandia-quindio.gov.co\r\nCorreo de notificaciones judiciales: notificacionjudicial@filandia-quindio.gov.co', 0, 0, '3226609951', 'Carrera 6 # 6-09', false, 'https://www.facebook.com/alcaldiadefilandiaq/?locale=es_LA', 'https://www.instagram.com/alcaldiadefilandiaoficial/', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/uWDD8g6W9LF7dRpz9', true),
	(2, 11, 8, 3, 'Valle de Cocora', 'valle-de-cocora', 'Parque pintoresco lleno de palmas de cera de más de 60 m en un entorno frondoso con senderismo y restaurantes.\r\nServicios\r\n\r\nColumpios\r\n\r\nMesas de pícnic\r\n\r\nSanitario público\r\n\r\nSe permiten perros\r\n\r\n \"Cuéntanos que nos encontraste en miquindio.com y te informaremos sobre nuestras promociones especiales.', 6, 0, '3102275091', 'Vía al Valle de Cocora, Km 11, Salento', false, 'https://www.facebook.com/valledecocora/?locale=es_LA', 'https://www.instagram.com/valledecocora_/?hl=es', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/YjD54qTMssFTJiLG6', true),
	(2, 6, 8, 3, 'Mirador Colina', 'mirador-colina', 'Esta ubicado en Filandia Quindío, es una torre fabricada en madera de 27 metros, construida con finas maderas de la región entre ellas mangle rolliza. En su interior se destaca una figura en retales de vidrio y espejo de una mariposa azul. Cuenta con varios puntos de observación con telescopios que apuntan hacia varios municipios cercanos.\r\n\r\nDesde la torre se puede observar el hermoso paisaje de filanda a 360° y en los dias despejados se puede divisar casi todos los municipios del Quindio, la ciudad de Pereira Risaralda y algunos pueblos del Norte del Valle. La torre cuenta Café Gaviota que abre los fines de semana su atención al publico para así disfrutar del mejor Café que produce el Quindío.', 6, 0, '67582195', 'filandia', false, 'https://www.facebook.com/@miradordefilandia/?locale=es_LA', 'https://www.instagram.com/explore/locations/239720371/mirador-colina-iluminada-filandia-quindio/?locale=es', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/W4pLtmF8LLhktiwo9', true),
	(2, 1, 8, 2, 'Museo del Oro', 'museo-del-oro', 'La entrada es gratuita y no requiere cita previa. \r\nReserva de visitas guiadas para grupos: \r\nBanrepculturalArmenia@banrep.gov.co\r\nhttps://www.banrepcultural.org/armenia/museo-del-oro-quimbaya/programe-su-visita', 4, 0, '6013430663', 'Avenida Bolívar # 40 norte – 80, en la rotonda del Ferrocarril', false, 'https://www.facebook.com/MuseoDelOroQuimbaya/', 'https://www.instagram.com/explore/locations/1018159406/museo-quimbaya-armenia/', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/x8UkH4i5u5YrDUn56', true),
	(2, 4, 8, 3, 'Cementerio Libre', 'cementerio-libre', 'Cementerio Libre de Circasia, uno de los mausoleos más característicos de los quindianos y una muestra de los ideales libertarios que se asentaron en esa ciudad, fundada con el nombre de La Plancha en 1884. El monumento fue inaugurado el 9 de octubre de 1933 bajo los auspicios de Braulio Botero Londoño, su promotor, como símbolo de la defensa a la libertad, la tolerancia y el amor.', 6, 0, 'np', 'circasia', false, 'https://www.facebook.com/groups/15535202524/?locale=es_LA', 'https://www.instagram.com/explore/locations/313910958943460/cementerio-libre-circasia-quindio/', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/qaVywkPmTbnjwbHTA', true),
	(2, 2, 8, 3, 'Casa en el Aire', 'casa-en-el-aire', 'A un paso del cielo ✨ Mirador & café ☕️\r\nEntrada $20.000 🎟️ Buenavista Quindío 🇨🇴 Fotos 📸\r\n10:00 am a 6:00 pm', 5, 0, '3145789684', 'Las Gurrías, Buenavista', false, 'https://www.facebook.com/casaenelairemirador', 'https://www.instagram.com/casaenelairemirador/?hl=es', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/j8oFv2XreehUEKHz6', true),
	(19, 4, 5, 1, 'San Rafael', 'san-rafael', 'Taller de pintura- velas aromáticas- Ceramicas para decorar el hogar- Imagenes religiosas- inciensos- sahumerios- flores inmortalizadas\r\nVisítanos en nuestras dos ubicaciones Carrera 12 6-78 local 4', 7, 0, '3185937042', 'Mall Doña Ana primer piso', false, 'https://www.facebook.com/profile.php?id=100071739064363&mibextid=LQQJ4d', 'https://www.instagram.com/velascircasiasanrafael/profilecard', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/g5HFzZ9ppDfMBtYs8?g_st=com.google.maps.preview.copy', true),
	(20, 4, 3, 2, 'Bremen La Pasion del Cafe', 'bremen-la-pasion-del-cafe', 'ven y disfruta del rico cafe que tenemos para que lo disfrute en pareja o con toda sus familia tambien tenemos un rico menua un excelente precio', 0, 0, '3113317247', 'calle 7 parque principal', false, 'https://web.facebook.com/p/Restaurante-CAFE-Bremen-100063725586157/?_rdc=1&_rdr', 'https://www.instagram.com/cafe_bremen_circasia/?hl=es-la', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/TVDbtaAaLASGqrWC7', false),
	(21, 4, 2, 1, 'Pijamas', 'pijamas', 'Hermosas pijamas \r\nPiel de durazno para dormir cómodamente', 14, 0, '3137994405', 'Barrio cooperativo MZ h casa 4', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(1, 9, 3, 1, 'Tama prueba', 'tamales-lucho', 'Tamales tolimenses en nuestro restaurante y a domicilio', 0, 0, '3009876543', 'Calle 1 # 10-22', true, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, false),
	(23, 4, 3, 1, 'Arepas de queso', 'arepas-de-queso', 'Prueba nuestro producto , las deliciosas arepas de queso con una tradicion de más de 30 años....', 9, 0, '3177275907', 'Calle 7 cra 14 esquina', false, 'https://www.instagram.com/arepasquesudas_?igsh=ZTRxY2E4dngzNHh2', 'https://www.instagram.com/arepasquesudas_?igsh=ZTRxY2E4dngzNHh2', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/R3NMt5418nzSvXpw5', true),
	(2, 1, 4, 1, 'mundocomputo', 'mundocomputo', 'Arma tu setup gamer con nuestos productos y componentes de la mejor calidad y al mejor precio', 8, 0, '3122924047', 'Carrera 14 # 3-81', false, 'https://www.facebook.com/mundocomputoarmenia/?locale=es_LA', 'https://www.instagram.com/mundocomputo/?hl=es', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/EUnzBua3W9dSXZqo9', true),
	(2, 5, 8, 3, 'La Casa al revés', 'la-casa-al-reves', 'Esta ubicada en el municipio de Córdoba Quindio, entrando después de la estación de combustible a mano derecha por el Skatepark del barrio Maria Teresa.\r\nEl parque cuenta con la casa completamente patas arriba y con una inclinación de 6 grados para mejorar la sensación en el interior, varias habitaciones, cocina, baño, las fotos y los videos que se logran solo girando el celular o la cámara son super divertidas pues dan la sensación de estar suspendidos del techo cabeza abajo, Qinti, el parque en las Montañas, cuenta con un espacio con varios willis, maya catamaran una zona de globos aerostaticos, varios miradores con muchos elementos para la foto, un restaurante donde se brindaran platos tipicos del municipio, un sendero de varios kilometros que conduce a una cascada.\r\nLa entrada al lugar tiene un costo de $30.000 y el servicio de parqueadero lo prestan los habitantes del sector en el barrio aledaño.', 2, 0, '3103794709', 'municipio de Córdoba Quindio, entrando después de la estación de combustible a mano derecha por el Skatepark del barrio Maria Teresa', false, NULL, 'https://www.instagram.com/qintiparque/?igshid=MmU2YjMzNjRlOQ%3D%3D&fbclid=IwY2xjawG7UK9leHRuA2FlbQIxMAABHdnqPTQYRnoui80QDr44K9cni4g8bGd2AFehhknogB-5yNb-0ACM_ApzhQ_aem_IcX2r5HMaTnw-lXMTugPDw', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/3hinWKt1BfTeyVCa8', true),
	(2, 8, 8, 3, 'Parque de los Arrieros', 'parque-de-los-arrieros', 'Es el mas nuevo de los parques temáticos del Quindio. Localizado en la vía entre Montenegro y Quimbaya.\r\n\r\nEn este parque podrá conocer y disfrutar lo mejor de toda la cultura de la arriería, que nace desde el mismo momento que los arrieros partieron de varios de los municipios de Antioquia, en lo que se conoce como el periodo de la Colonización Antioqueña.\r\n\r\nEn los últimos años este importante atractivo turístico, empieza a tener un lugar importante en la categoría de sitios turisticos en el Quindio.', 3, 0, '3113448451', 'Carrera 4 No 23 55 Barrio La Pista', false, 'https://www.facebook.com/parquelosarrieros/?locale=es_LA', 'https://www.instagram.com/parquelosarrieros/?hl=es', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/5DVFftN4HtPJYFsj8', true),
	(2, 11, 8, 3, 'Finca El Ocaso Salento Quindio', 'finca-el-ocaso-salento-quindio', 'Somos una finca productora de café especial en donde mostramos todo el proceso del café de una manera auténtica y artesanal.', 3, 0, '3134253669', 'Km 3.8 via Salento Vereda Palestina', false, 'https://www.facebook.com/fincaelocasosalento/?locale=es_LA', 'https://www.instagram.com/fincaelocasosalento/?fbclid=IwY2xjawG7VvdleHRuA2FlbQIxMAABHe1T6ImVTs0YLa2Wayml8KPGTCtqn_M5ezi9_uP-vnGi50eJNeGCekOxeQ_aem_jXtA4yxe4nE55VKC8yKtZg', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/woik2fh7CDKfUEni6', true),
	(2, 2, 8, 3, 'Café San Alberto', 'cafe-san-alberto', 'En medio de los campos de café de la Hacienda y rodeados por un paisaje mágico, puede disfrutar de una deliciosa taza de café. Aproveche al máximo su visita', 3, 0, '3168271421', 'Cra. 2, Buenavista', false, 'https://www.facebook.com/cafesanalberto', 'https://www.instagram.com/cafe_san_alberto/?igshid=YmMyMTA2M2Y%3D', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/pRDu8v2fTcXaugGz6', true),
	(2, 3, 8, 3, 'Parapente en Calarcá Quindío', 'parapente-en-calarca-quindio', 'Despega de increíbles montañas y vive la magia! Sin aviones, sin motores, sin turbinas, vive con nosotros una increíble aventura extrema llena de adrenalina y emociones sin límites.', 3, 0, '3235234809', 'Calarcá', false, 'https://www.facebook.com/quindioextremo.quindioextremo?_ga=2.6523703.462768972.1733196674-1404900363.1733196674&_gac=1.144828800.1733196674.EAIaIQobChMIzI32stSKigMVpKBaBR3Z8yCpEAMYASAAEgIQDfD_BwE', 'https://www.instagram.com/parapentecolombia_/?hl=es-la&_ga=2.35874341.462768972.1733196674-1404900363.1733196674&_gac=1.237839028.1733196674.EAIaIQobChMIzI32stSKigMVpKBaBR3Z8yCpEAMYASAAEgIQDfD_BwE', NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(2, 8, 8, 3, 'El Paraíso Del Bambú y la Guadua', 'el-paraiso-del-bambu-y-la-guadua', 'Finca El Bambusal, vereda La Esmeralda\r\nPor la entrada del Hotel las Camelias\r\nCorregimiento Pueblo Tapado\r\nMontenegro, Quindío, Colombia\r\nAtendemos con cita previa de 9 am a 4 pm', 0, 0, '316 241 1412', 'Finca la Esmeralda, Vereda el Bambusal, Pueblo Tapado', false, 'https://www.facebook.com/paraisobambuyguadua', 'https://www.instagram.com/paraisobambuyguadua/', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/Yza5jinrZZeNnPT46', true),
	(2, 12, 17, 2, 'Coffee Shop La Tienda de los Mecatos', 'coffee-shop-la-tienda-de-los-mecatos', 'Ofrecemos experiencias únicas que permiten a los viajeros sentir, ver, probar, oler, oír, disfrutar y comprender el mundo del campo con su cultura y otras', 9, 0, '3155472368', 'Km 6 Vía El Edén - Armenia, Quindío Colombia', false, 'https://www.facebook.com/coffeeshoplatiendadelosmecatos', 'https://www.instagram.com/CoffeeShopLaTIendadelosMecatos/', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/SiXWzScRiAgJGhYX7', true),
	(2, 11, 8, 3, 'Finca Buenos Aires', 'finca-buenos-aires', 'Mágicos lugares donde podrás apreciar los verdes paisajes cafeteros,rico en flora y fauna,el susurro de los guaduales y el canto de aves endémicas.', 1, 0, '3172408335', 'Vereda Llano Grande, a 2.5 Kilómetros de la autopista del café por la vereda los pinos o a 6 kilómetros desde Salento por la vereda palestina', false, 'https://www.facebook.com/Finca.buenosaires.Salento.Quindio/', 'https://www.instagram.com/finca_buenosaires/?hl=es-la', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/J9tQnwvCHUeGWhoc9', true),
	(2, 4, 8, 2, 'Horario Bus Montenegro Circasia', 'horario-bus-montenegro-circasia', 'Horario de Despachos\r\nDe Lunes a Sábado\r\nA partir del 17 de Octubre\r\n\r\nSalida desde Montenegro:\r\n\r\n05:20 AM\r\n\r\n06:10 AM\r\n\r\n07:10 AM\r\n\r\n08:10 AM\r\n\r\n09:10 AM\r\n\r\n10:10 AM\r\n\r\n11:10 AM\r\n\r\n12:10 PM\r\n\r\n01:10 PM\r\n\r\n02:10 PM\r\n\r\n03:10 PM\r\n\r\n04:10 PM\r\n\r\n05:10 PM\r\n\r\n06:20 PM\r\n\r\n\r\n\r\n\r\nSalida desde Circasia:\r\n06:00 AM\r\n\r\n07:10 AM\r\n\r\n08:10 AM\r\n\r\n09:10 AM\r\n\r\n10:10 AM\r\n\r\n11:10 AM\r\n\r\n12:10 PM\r\n\r\n01:10 PM\r\n\r\n02:10 PM\r\n\r\n03:10 PM\r\n\r\n04:10 PM\r\n\r\n05:10 PM\r\n\r\n06:20 PM', 4, 0, '3223928696', 'armenia', true, 'https://www.facebook.com/transarmeniacarga/', 'https://www.instagram.com/cargatransarmenia/?hl=es-la', NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(24, 12, 8, 1, 'Artesanías', 'artesanias', 'Artesanias típicas ,como llaveros ,imanes, portallaves,portalapiceros y mucho mas.', 10, 0, '3167907555', 'Cra 6 #10 73', false, 'Crearteyv', 'Crearte_y_v', NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(25, 4, 3, 2, 'Artelac-el arte de la leche', 'artelac-el-arte-de-la-leche', 'Productos Artesanales hechos con amor, además encontrarás postres, bebidas frías y calientes\r\nHorario \r\nLunes cerrados\r\nMartes a Viernes 8:30am-12:00pm y 2:00pm-6:00pm\r\nSábado - lunes festivo 8:00am-6:00pm', 13, 0, '3104225731', 'Km 3.4 vereda llanadas vía circasia Montenegro al lado del Caney', false, NULL, 'https://www.instagram.com/artelacq/profilecard/?igsh=MWV4bnFsYjRsaXl0bQ==', NULL, NULL, NULL, NULL, '2025-08-02', 'https://www.google.com/maps/place/Artelac,+Finca+Sebastopol,+Km.+3+via+Circasia-Montenegro,+Circasia,+Quind%C3%ADo/@4.600395,-75.6631252,17z/data=!4m6!3m5!1s0x8e388bd18d82e8c5:0x7560497545592c21!8m2!3d4.600395!4d-75.6631252!16s%2Fg%2F11vl5djwqp?hl=es', true),
	(26, 3, 3, 1, 'Restaurante la cascada', 'restaurante-la-cascada', 'Descubre la magia de la cascada, un restaurante que te transporta a un oasis de sabor y tranquilidad.Disfruta de nuestra cocina Gourmet, inspirada en la naturaleza y la tradición, en un ambiente acogedor y rodeado de belleza natural. ¡Ven y déjanos sorprenderte!', 6, 0, '3185997651', 'Cra 24 40-41', false, 'https://www.facebook.com/share/15qveUB71n/?mibextid=LQQJ4d', 'https://www.instagram.com/restaurante_lacascada/profilecard/?igsh=MTdkbmQyZWxydmdjaQ==', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/8kYb6oVoVrL4o7Yu9?g_st=com.google.maps.preview.copy', true),
	(27, 3, 17, 2, 'Café con sabor a recuerdos', 'cafe-con-sabor-a-recuerdos', 'La ruana calarcá es un lugar acogedor y lleno de tradición para compartir en familia .', 23, 0, '3168598292', 'Carrera 25 # 41 - 49', false, NULL, '@laruanacalarca', NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(29, 4, 2, 1, 'ZH Cueros', 'zh-cueros', 'Ubicados en el corazón de Circasia, Quindío, somos más que un punto de venta; somos un espacio donde la pasión por el cuero y la artesanía se encuentran con las últimas tendencias. explorando nuestra exclusiva colección de bolsos, carteras, zapatos y accesorios. Cada pieza refleja calidad, elegancia y el compromiso con un trabajo bien hecho.', 10, 0, '3104220131', 'CARRERA 14 #5-51', true, NULL, 'https://www.instagram.com/zhcueros/profilecard/?igsh=ZDZyOG1yaWl6cmp0', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/N9odV3XBLrTEiigJ8', true),
	(28, 4, 2, 1, 'Venta de tennis', 'venta-de-tennis', 'Venta de tennis importados', 21, 0, '300 5595658', 'Tienda digital', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(29, 4, 3, 1, 'Kiosko martin', 'kiosko-martin', 'Te ofrecemos arepas,dedos,sándwich,desayunos,jugo de naranja,chocolate ....\r\n\r\nNo te pierdas nuestros buñuelos de maíz...', 4, 0, '3147407161', 'Al lado de la escuelita Consuelo Betancourth', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(2, 4, 1, 2, 'Clínica Dental Sonreir', 'clinica-dental-sonreir', 'Ofrecemos servicios de odontología de alta calidad en un ambiente cálido y profesional. Nuestro equipo de expertos se dedica a cuidar tu salud dental y a brindarte la sonrisa que mereces. ¡Visítanos y experimenta la diferencia!', 8, 0, '3113641574', 'paque principal', false, '1', '1', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/9hcGq3PoqECtjP799', true),
	(2, 4, 3, 1, 'Don Papa', 'don-papa', 'Nos complace ofrecerte licores locales e importados de la mejor calidad a precios excelentes. Disfruta de la mejor música en un ambiente acogedor, ideal para pasar un rato agradable con tus amigos.', 2, 0, '321 5618314', 'Clle 6 # 13 31', false, NULL, '1', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/MdUBpKF6e7SpKZQaA', true),
	(22, 4, 3, 1, 'La Casa del Pandebono', 'la-casa-del-pandebono-en-circasia', 'La Casa del Pandebono te invita a disfrutar de nuestros irresistibles pan pizzas, recién horneadas y disponibles a cualquier hora de la tarde. Ven y deléitate con el sabor único que solo nosotros te podemos ofrecer. ¡Te esperamos con los brazos abiertos', 5, 0, '3182832558', 'Cra 15 # 8-73', false, 'https://www.facebook.com/lacasadelpandebono.pandebono?locale=es_LA', NULL, NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/mL6QKvt9tX6VkEvp8', true),
	(30, 3, 2, 2, 'Ropa para gym', 'ropa-para-gym', 'Ropa, accesorios, calzados para deporte', 5, 0, '3126417591', 'CRA 25 # 25-27 primer piso', true, 'Fit life shop', 'Fit_life_shoop', NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(2, 4, 21, 2, 'Flota occidental Horarios', 'flota-occidental-horarios', '', 10, 0, '3122879555', 'circasia', false, 'https://www.facebook.com/flotaoccidental/?locale=es_LA', 'https://www.instagram.com/flotaoccidental/?hl=es', NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(31, 11, 3, 1, 'Miscelánea Emmanuel', 'miscelanea-emmanuel', 'Verduras, frutas,granos, lateos, dulcería, bebidas y demás productos', 5, 0, '3108396986', 'Carrera cuarta barrio las colinas #151subida mirador Salento Quindío', false, 'https://www.facebook.com/yury.marin.967?mibextid=ZbWKwL', NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(2, 4, 21, 2, 'Inter rapidísimo', 'inter-rapidisimo', '', 8, 0, '3184965409 - 3237101748', 'Calle 8 numero 9 83', true, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(33, 4, 18, 2, 'DJ barber chop', 'dj-barber-chop', 'Se realizan cortes de cabello', 10, 0, '3234022377', 'Carra 13 #7-03', true, 'https://www.facebook.com/share/14kTk2bZg4/', 'https://www.instagram.com/jhoanyledesma/profilecard/?igsh=MXJ3Nnhxd3VldXFzbQ==', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/m4q6uLWZhLjJJryM6', true),
	(2, 4, 21, 2, 'Envía', 'envia', 'Envia Colombia es una empresa de mensajería y envíos que se destaca por ofrecer soluciones logísticas tanto a nivel nacional como internacional. Su servicio está enfocado en proporcionar una entrega rápida, segura y confiable de paquetes y documentos', 0, 0, '23659024', 'Cl. 6 #12, 67', true, NULL, 'https://www.instagram.com/envia.co/', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/aQ6zB4kmUVRxebBR7', true),
	(2, 4, 21, 2, 'Efecty Servientrega', 'efecty-servientrega', 'Servientrega es una de las empresas de mensajería y logística más reconocidas en Colombia y América Latina. Se especializa en el transporte de paquetes y documentos', 1, 0, '0', 'Cl. 6 #14-74', true, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/jRoDVpmcKeY4SVk76', true),
	(2, 4, 21, 2, 'Bomberos', 'bomberos', 'Los bomberos son profesionales encargados de prevenir, controlar y extinguir incendios, así como de asistir en situaciones de emergencia y rescate. Su labor es fundamental para proteger la vida, los bienes y el medio ambiente', 5, 0, '3134974209', NULL, true, 'https://www.facebook.com/profile.php?id=61554087545176&sk=about', NULL, NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/KEY5CwAgpS4GNeeT8', true),
	(32, 4, 5, 1, 'Floristería y Detalles Alejandra', 'floristeria-y-detalles-alejandra', 'Arreglos florales toda ocasión, desde conquistar tú amor, hasta despedir tu ser querido.', 8, 0, '3122212612', 'Crr 16 # 5-15', true, 'https://www.facebook.com/share/19Cw84FWXq/', 'https://www.instagram.com/alejandrafloristeriaydetalles/profilecard/?igsh=Y2R1YzAzcTAzcnM4', NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(34, 4, 5, 1, 'Jabón Todero Multiusos', 'jabon-todero-multiusos', 'Jabón en crema y liquido Todero multiusos. \r\nBRILLA,DESPERCUDE,DESMANCHA,DESENGRASA Y CUIDA TUS MANOS.', 25, 0, '3017159364', 'Solo por Whatsapp o llamada.', true, 'https://www.facebook.com/Toderojabonencremamultiusos?mibextid=ZbWKwL', NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(35, 4, 7, 2, 'Masajes tu negra sabrosa', 'masajes-tu-negra-sabrosa', 'Limpieza facial con chocolaterapia', 9, 0, '3107055902', 'Wasap ..audios.', true, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(35, 4, 20, 2, 'Se busca barista', 'se-busca-barista', 'Se busca barista tiempo completo en circasia', 7, 0, '3107055902', 'Wasap ..audios.', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(35, 4, 20, 2, 'Cosina', 'cosina', 'Se busca chica para trabajar..que le guste cocinar..y le guste trabajar en equipo.', 4, 0, '3107055902', 'Wasap ..audios.', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, false),
	(37, 4, 11, 1, 'Plataformas Streaming', 'plataformas-streaming', 'Netflix $14.000\r\nHbo max $10.000\r\nAmazon Prime $10.000', 9, 0, '3185032838', 'Calle 2', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(36, 4, 7, 1, 'Fraiche "Perfumes y esencias"', 'fraiche-perfumes-y-esencias', 'En fraiche ofrecemos una amplia variedad de productos de fragancias para satisfacer tus necesidades. Nuestra colección incluye: \r\n\r\n- Más de 200 fragancias. Unisex, niñ@s, dama y caballeros.\r\n- splash para caballero, dama, niñ@s y mascotas\r\n- Desodorantes y cremas humectantes. Se agrega el aroma de tu preferencia. \r\n- Velas aromatizadas y difusores para el hogar \r\n- Ambientadores para el hogar, automóviles y la ropa \r\n- kits para detalles y mucho más', 4, 0, '3225692512', 'Calle 8 #14 -05 local 2 - frente al Super inter', false, 'https://www.facebook.com/fraichecalarcacircasiacaicedon?mibextid=ZbWKwL', 'https://www.instagram.com/fraichecalarcacircasiacaicedon?igsh=YzljYTk1ODg3Zg==', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/psVdwf6EHqGTvWD86', true),
	(36, 3, 7, 1, 'Fraiche "Perfumes y esencias "', 'graiche-perfumes-y-esencias', 'En fraiche ofrecemos una amplia variedad de productos de fragancias para satisfacer tus necesidades. Nuestra colección incluye: \r\n\r\n- Más de 200 fragancias Unisex, niñ@s, dama y caballeros\r\n- splash para caballero, dama, niñ@s y mascotas\r\n- Desodorantes y cremas humectantes. Se agrega el aroma de tu preferencia. \r\n- Velas aromatizadas y difusores para el hogar \r\n- Ambientadores para el hogar, automóviles y la ropa \r\n- kits para detalles y mucho más', 4, 0, '3224692511', 'Calle 8 #14 -05 local 2 - frente al Super inter', false, 'https://www.facebook.com/fraichecalarcacircasiacaicedon?mibextid=ZbWKwL', 'https://www.instagram.com/fraichecalarcacircasiacaicedon?igsh=YzljYTk1ODg3Zg==', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/csqX1Kpmv4ct9Zeo6?g_st=ac', true),
	(39, 4, 3, 1, 'La vinería', 'la-vineria', 'La vineria, es una tienda virtual que ofrece variedad de vinos, que se convierten en detalles para celebrar momentos especiales. Aquí, se le permite al cliente personalizar su propia botella de vino, la cual es entregada en la ubicación que se indique al momento de realizar la compra.', 4, 0, '3012451694', NULL, true, 'https://www.facebook.com/share/1BAiZUgbcg/?mibextid=wwXIfr', 'https://www.instagram.com/lavineria_col?igsh=MTZqdDh6YTQyMDdjOA==', NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(39, 4, 3, 1, 'Panadería Uraku', 'panaderia-uraku', 'Somos una panadería con productos siempre frescos y de excelente calidad', 3, 0, '3012186984', 'Calle 8 # 11-71', false, 'https://www.facebook.com/share/1K1YESvmbV/?mibextid=wwXIfr', 'https://www.instagram.com/urakusabordehogar?igsh=cGN5NXk5Mzk5Y3hx', NULL, NULL, NULL, NULL, '2025-08-02', 'Cl. 8 #11-71', true),
	(40, 4, 3, 1, 'Miss papa', 'miss-papa', 'Papas 100% naturales con toppings + dorimontañeros', 1, 0, '3195073545', 'Crr 14 al lado de Juana de Juana', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, false),
	(41, 1, 20, 2, 'Cuidadora', 'cuidadora', 'Ofrecer mis servicios como cuidadora para personas hospitalizadas.', 8, 0, '3133812451', 'Villa Sofia', true, 'https://www.facebook.com/share/18YrMbsCNa/', 'https://www.instagram.com/videsyolibeth/profilecard/?igsh=dHZwbjB2bTBmMm9j', NULL, NULL, NULL, NULL, '2025-08-02', 'Armenia Quindío', true),
	(42, 4, 3, 1, 'Travesias Restaurante & Parrilla', 'travesias-restaurante-parrilla', 'Los invitamos a visitarnos. Nuestra especialidad son los platos al horno, cortes de parrilla, pescados, cazuela Travesías y variedad de menú ejecutivo.', 6, 0, '3122131514', 'Cra. 15 9 50', true, 'https://www.facebook.com/travesiasfood?mibextid=kFxxJD', 'https://www.instagram.com/travesiasrestaurante?igsh=aTFpbnNzODltZGxu', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/B8VHHJe2HdW2zbjf8', false),
	(43, 4, 19, 1, 'Agropecuaria samy', 'agropecuaria-samy', 'Venta de todo lo relacionado para tu mascota', 3, 0, '3108417089', 'Cra 15 # 9-54', true, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(44, 4, 3, 1, 'HELADERÍA LA GOLOSA', 'heladeria-la-golosa', '', 5, 0, '3133870571', 'Calle 6 #15-36', true, NULL, 'https://www.instagram.com/lagolosa_2024?igsh=ZHlpYm5lNzh2Ymxw', NULL, NULL, NULL, NULL, '2025-08-02', 'https://maps.app.goo.gl/9HHNKH9gXpsQovaF9', true),
	(45, 4, 3, 1, 'Siempre Alegre Market Circasia', 'siempre-alegre-market-circasia', 'Rancho- Licores-Dulces y chocolates- Víveres y abarrotes', 11, 0, '3155634042', 'Calle 7 Nro 16-10 Esquina', true, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(38, 4, 11, 1, 'Venta cuentas streaming', 'venta-cuentas-streaming', 'Todo tipo de cuentas streaming a buen precio y garantizado\r\n\r\nPregunta por tu preferida', 3, 0, '+57 3192237115', 'Circasia Quindío', false, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-02', NULL, true),
	(38, 4, 7, 2, 'Maquilladora profesional', 'maquilladora-profesional', 'Maquilladora profesional \r\n\r\n* Cursos personalizados de maquillaje \r\n\r\n* Maquillaje profesional para todo tipo de ocasión a precios accesibles \r\n\r\n* Keratinas y repolarizacion a bajo costo \r\n\r\n* Diseño de cejas segun morfología de tu rostro\r\n\r\n* Depilacion de cejas, bigote, axilas, media pierna, pierna completa, cotiza sin compromiso \r\n\r\n* Sombreado de cejas en Henna \r\n\r\n* Laminado de cejas \r\n\r\n* Lifting de pestañas \r\n\r\n* Pestañas punto a punto \r\n\r\n* Venta productos de belleza \r\n\r\nCircasia Armenia', 5, 0, '+57 (314) 762-05-30 +57 (319) 223-71-15', 'Circasia Quindío', false, NULL, 'https://www.instagram.com/yulianaa.makeup?igsh=NTc4MTIwNjQ2YQ==', NULL, NULL, NULL, NULL, '2025-08-02', NULL, true);

INSERT INTO public.images (url, post_id) VALUES
	('uploads/images/posts/consultorio-mshelle-montoya/0.jpeg', 1),
	('uploads/images/posts/consultorio-mshelle-montoya/1.jpeg', 1),
	('uploads/images/posts/consultorio-mshelle-montoya/2.jpeg', 1),
	('uploads/images/posts/carnes-mickey/0.jpeg', 2),
	('uploads/images/posts/detallitos-fashion/0.jpeg', 3),
	('uploads/images/posts/en-madas-food/0.jpeg', 4),
	('uploads/images/posts/barenque/0.jpeg', 5),
	('uploads/images/posts/la-selecta/0.jpeg', 6),
	('uploads/images/posts/pollo-dorado/0.jpeg', 7),
	('uploads/images/posts/naranja-dulce/0.jpeg', 8),
	('uploads/images/posts/belleza-integral/0.jpeg', 9),
	('uploads/images/posts/carnes-mi-pueblito/0.jpeg', 10),
	('uploads/images/posts/lima-azul/0.jpeg', 11),
	('uploads/images/posts/detallitos-fashion/1.jpeg', 3),
	('uploads/images/posts/detallitos-fashion/2.jpeg', 3),
	('uploads/images/posts/detallitos-fashion/3.jpeg', 3),
	('uploads/images/posts/detallitos-fashion/4.jpeg', 3),
	('uploads/images/posts/detallitos-fashion/5.jpeg', 3),
	('uploads/images/posts/impresiones-3d/0.jpeg', 12),
	('uploads/images/posts/impresiones-3d/1.jpeg', 12),
	('uploads/images/posts/tecnopolis/0.jpeg', 13),
	('uploads/images/posts/tecnopolis/1.jpeg', 13),
	('uploads/images/posts/tecnopolis/2.jpeg', 13),
	('uploads/images/posts/fundacion-genios/0.jpeg', 14),
	('uploads/images/posts/fundacion-genios/1.jpeg', 14),
	('uploads/images/posts/fundacion-genios/2.jpeg', 14),
	('uploads/images/posts/fundacion-genios/3.jpeg', 14),
	('uploads/images/posts/fundacion-genios/4.jpeg', 14),
	('uploads/images/posts/todo-en-deportes/0.jpeg', 15),
	('uploads/images/posts/todo-en-deportes/1.jpeg', 15),
	('uploads/images/posts/venda-de-celular-samsung-galaxy-a22/0.jpeg', 16),
	('uploads/images/posts/venda-de-celular-samsung-galaxy-a22/1.jpeg', 16),
	('uploads/images/posts/venda-de-celular-samsung-galaxy-a22/2.jpeg', 16),
	('uploads/images/posts/venda-de-celular-samsung-galaxy-a22/3.jpeg', 16),
	('uploads/images/posts/summer-cafe-prueba/0.jpeg', 17),
	('uploads/images/posts/hotel-vivienda-turistica/0.jpeg', 18),
	('uploads/images/posts/ropa-fina-buenavista/0.jpeg', 19),
	('uploads/images/posts/quindiaroma/0.jpeg', 20),
	('uploads/images/posts/quindiaroma/1.jpeg', 20),
	('uploads/images/posts/quindiaroma/2.jpeg', 20),
	('uploads/images/posts/musa-reposteria/0.jpeg', 21),
	('uploads/images/posts/the-empanadas-crispy/0.jpeg', 22),
	('uploads/images/posts/dulce-regalo/0.jpeg', 23),
	('uploads/images/posts/kaffa-la-aldea/0.jpeg', 24),
	('uploads/images/posts/kaffa-la-aldea/1.jpeg', 24),
	('uploads/images/posts/kaffa-la-aldea/2.jpeg', 24),
	('uploads/images/posts/kaffa-la-aldea/3.jpeg', 24),
	('uploads/images/posts/kaffa-la-aldea/4.jpeg', 24),
	('uploads/images/posts/bicicleta/0.jpeg', 25),
	('uploads/images/posts/bicicleta/1.jpeg', 25),
	('uploads/images/posts/guacaticos/0.jpeg', 26),
	('uploads/images/posts/boutique-talu/0.jpeg', 27),
	('uploads/images/posts/almacen-de-bicicletas-sport-bici/0.jpeg', 28),
	('uploads/images/posts/dra-cristina-garcia-g-odontologia-integral-y-especializada/0.jpeg', 29),
	('uploads/images/posts/dra-cristina-garcia-g-odontologia-integral-y-especializada/1.jpeg', 29),
	('uploads/images/posts/dra-cristina-garcia-g-odontologia-integral-y-especializada/2.jpeg', 29),
	('uploads/images/posts/dra-cristina-garcia-g-odontologia-integral-y-especializada/3.jpeg', 29),
	('uploads/images/posts/maquillaje/0.jpeg', 30),
	('uploads/images/posts/la-greca-cafe-bar/0.jpeg', 31),
	('uploads/images/posts/opticas-tinoco/0.jpeg', 32),
	('uploads/images/posts/el-baul-de-chimuelo/0.jpeg', 33),
	('uploads/images/posts/el-baul-de-chimuelo/1.jpeg', 33),
	('uploads/images/posts/el-baul-de-chimuelo/2.jpeg', 33),
	('uploads/images/posts/el-baul-de-chimuelo/3.jpeg', 33),
	('uploads/images/posts/el-baul-de-chimuelo/4.jpeg', 33),
	('uploads/images/posts/parque-del-cafe/0.jpeg', 34),
	('uploads/images/posts/panaca/0.jpeg', 35),
	('uploads/images/posts/jardinbotanicoquindio/0.jpeg', 36),
	('uploads/images/posts/bahialoft/0.jpeg', 37),
	('uploads/images/posts/parque-de-la-vida/0.jpeg', 38),
	('uploads/images/posts/alcaldia-de-circasia/0.jpeg', 39),
	('uploads/images/posts/alcaldia-de-filandia/0.jpeg', 40),
	('uploads/images/posts/valle-de-cocora/0.jpeg', 41),
	('uploads/images/posts/mirador-colina/0.jpeg', 42),
	('uploads/images/posts/museo-del-oro/0.jpeg', 43),
	('uploads/images/posts/cementerio-libre/0.jpeg', 44),
	('uploads/images/posts/casa-en-el-aire/0.jpeg', 45),
	('uploads/images/posts/san-rafael/0.jpeg', 46),
	('uploads/images/posts/san-rafael/1.jpeg', 46),
	('uploads/images/posts/san-rafael/2.jpeg', 46),
	('uploads/images/posts/san-rafael/3.jpeg', 46),
	('uploads/images/posts/san-rafael/4.jpeg', 46),
	('uploads/images/posts/bremen-la-pasion-del-cafe/0.jpeg', 47),
	('uploads/images/posts/pijamas/0.jpeg', 48),
	('uploads/images/posts/pijamas/1.jpeg', 48),
	('uploads/images/posts/pijamas/2.jpeg', 48),
	('uploads/images/posts/pijamas/3.jpeg', 48),
	('uploads/images/posts/pijamas/4.jpeg', 48),
	('uploads/images/posts/pijamas/5.jpeg', 48),
	('uploads/images/posts/pijamas/6.jpeg', 48),
	('uploads/images/posts/pijamas/7.jpeg', 48),
	('uploads/images/posts/pijamas/8.jpeg', 48),
	('uploads/images/posts/pijamas/9.jpeg', 48),
	('uploads/images/posts/pijamas/10.jpeg', 48),
	('uploads/images/posts/pijamas/11.jpeg', 48),
	('uploads/images/posts/pijamas/12.jpeg', 48),
	('uploads/images/posts/pijamas/13.jpeg', 48),
	('uploads/images/posts/pijamas/14.jpeg', 48),
	('uploads/images/posts/pijamas/15.jpeg', 48),
	('uploads/images/posts/pijamas/16.jpeg', 48),
	('uploads/images/posts/tamales-lucho/0.jpeg', 49),
	('uploads/images/posts/tamales-lucho/1.jpeg', 49),
	('uploads/images/posts/tamales-lucho/2.jpeg', 49),
	('uploads/images/posts/tamales-lucho/3.jpeg', 49),
	('uploads/images/posts/tamales-lucho/4.jpeg', 49),
	('uploads/images/posts/tamales-lucho/5.jpeg', 49),
	('uploads/images/posts/tamales-lucho/6.jpeg', 49),
	('uploads/images/posts/tamales-lucho/7.jpeg', 49),
	('uploads/images/posts/tamales-lucho/8.jpeg', 49),
	('uploads/images/posts/tamales-lucho/9.jpeg', 49),
	('uploads/images/posts/arepas-de-queso/0.jpeg', 50),
	('uploads/images/posts/arepas-de-queso/1.jpeg', 50),
	('uploads/images/posts/arepas-de-queso/2.jpeg', 50),
	('uploads/images/posts/arepas-de-queso/3.jpeg', 50),
	('uploads/images/posts/arepas-de-queso/4.jpeg', 50),
	('uploads/images/posts/mundocomputo/0.jpeg', 51),
	('uploads/images/posts/la-casa-al-reves/0.jpeg', 52),
	('uploads/images/posts/parque-de-los-arrieros/0.jpeg', 53),
	('uploads/images/posts/finca-el-ocaso-salento-quindio/0.jpeg', 54),
	('uploads/images/posts/cafe-san-alberto/0.jpeg', 55),
	('uploads/images/posts/parapente-en-calarca-quindio/0.jpeg', 56),
	('uploads/images/posts/el-paraiso-del-bambu-y-la-guadua/0.jpeg', 57),
	('uploads/images/posts/coffee-shop-la-tienda-de-los-mecatos/0.jpeg', 58),
	('uploads/images/posts/finca-buenos-aires/0.jpeg', 59),
	('uploads/images/posts/horario-bus-montenegro-circasia/0.jpeg', 60),
	('uploads/images/posts/artesanias/0.jpeg', 61),
	('uploads/images/posts/artesanias/1.jpeg', 61),
	('uploads/images/posts/artesanias/2.jpeg', 61),
	('uploads/images/posts/artesanias/3.jpeg', 61),
	('uploads/images/posts/artesanias/4.jpeg', 61),
	('uploads/images/posts/artesanias/5.jpeg', 61),
	('uploads/images/posts/restaurante-la-cascada/0.jpeg', 63),
	('uploads/images/posts/restaurante-la-cascada/1.jpeg', 63),
	('uploads/images/posts/restaurante-la-cascada/2.jpeg', 63),
	('uploads/images/posts/restaurante-la-cascada/3.jpeg', 63),
	('uploads/images/posts/restaurante-la-cascada/4.jpeg', 63),
	('uploads/images/posts/restaurante-la-cascada/5.jpeg', 63),
	('uploads/images/posts/restaurante-la-cascada/6.jpeg', 63),
	('uploads/images/posts/restaurante-la-cascada/7.jpeg', 63),
	('uploads/images/posts/restaurante-la-cascada/8.jpeg', 63),
	('uploads/images/posts/restaurante-la-cascada/9.jpeg', 63),
	('uploads/images/posts/restaurante-la-cascada/10.jpeg', 63),
	('uploads/images/posts/restaurante-la-cascada/11.jpeg', 63),
	('uploads/images/posts/restaurante-la-cascada/12.jpeg', 63),
	('uploads/images/posts/cafe-con-sabor-a-recuerdos/0.jpeg', 64),
	('uploads/images/posts/cafe-con-sabor-a-recuerdos/1.jpeg', 64),
	('uploads/images/posts/cafe-con-sabor-a-recuerdos/2.jpeg', 64),
	('uploads/images/posts/cafe-con-sabor-a-recuerdos/3.jpeg', 64),
	('uploads/images/posts/cafe-con-sabor-a-recuerdos/4.jpeg', 64),
	('uploads/images/posts/cafe-con-sabor-a-recuerdos/5.jpeg', 64),
	('uploads/images/posts/zh-cueros/0.jpeg', 65),
	('uploads/images/posts/zh-cueros/1.jpeg', 65),
	('uploads/images/posts/zh-cueros/2.jpeg', 65),
	('uploads/images/posts/venta-de-tennis/0.jpeg', 66),
	('uploads/images/posts/venta-de-tennis/1.jpeg', 66),
	('uploads/images/posts/venta-de-tennis/2.jpeg', 66),
	('uploads/images/posts/venta-de-tennis/3.jpeg', 66),
	('uploads/images/posts/venta-de-tennis/4.jpeg', 66),
	('uploads/images/posts/venta-de-tennis/5.jpeg', 66),
	('uploads/images/posts/kiosko-martin/0.jpeg', 67),
	('uploads/images/posts/artelac-el-arte-de-la-leche/0.jpeg', 62),
	('uploads/images/posts/artelac-el-arte-de-la-leche/1.jpeg', 62),
	('uploads/images/posts/artelac-el-arte-de-la-leche/2.jpeg', 62),
	('uploads/images/posts/artelac-el-arte-de-la-leche/3.jpeg', 62),
	('uploads/images/posts/artelac-el-arte-de-la-leche/4.jpeg', 62),
	('uploads/images/posts/don-papa/0.jpeg', 69),
	('uploads/images/posts/la-casa-del-pandebono-en-circasia/0.jpeg', 70),
	('uploads/images/posts/clinica-dental-sonreir/0.jpeg', 68),
	('uploads/images/posts/la-casa-del-pandebono-en-circasia/1.jpeg', 70),
	('uploads/images/posts/la-casa-del-pandebono-en-circasia/2.jpeg', 70),
	('uploads/images/posts/la-casa-del-pandebono-en-circasia/3.jpeg', 70),
	('uploads/images/posts/la-casa-del-pandebono-en-circasia/4.jpeg', 70),
	('uploads/images/posts/la-casa-del-pandebono-en-circasia/5.jpeg', 70),
	('uploads/images/posts/la-casa-del-pandebono-en-circasia/6.jpeg', 70),
	('uploads/images/posts/la-casa-del-pandebono-en-circasia/7.jpeg', 70),
	('uploads/images/posts/la-casa-del-pandebono-en-circasia/8.jpeg', 70),
	('uploads/images/posts/la-casa-del-pandebono-en-circasia/9.jpeg', 70),
	('uploads/images/posts/ropa-para-gym/0.jpeg', 71),
	('uploads/images/posts/ropa-para-gym/1.jpeg', 71),
	('uploads/images/posts/ropa-para-gym/2.jpeg', 71),
	('uploads/images/posts/ropa-para-gym/3.jpeg', 71),
	('uploads/images/posts/ropa-para-gym/4.jpeg', 71),
	('uploads/images/posts/ropa-para-gym/5.jpeg', 71),
	('uploads/images/posts/flota-occidental-horarios/0.jpeg', 72),
	('uploads/images/posts/flota-occidental-horarios/1.jpeg', 72),
	('uploads/images/posts/flota-occidental-horarios/2.jpeg', 72),
	('uploads/images/posts/flota-occidental-horarios/3.jpeg', 72),
	('uploads/images/posts/miscelanea-emmanuel/0.jpeg', 73),
	('uploads/images/posts/inter-rapidisimo/0.jpeg', 74),
	('uploads/images/posts/inter-rapidisimo/1.jpeg', 74),
	('uploads/images/posts/inter-rapidisimo/2.jpeg', 74),
	('uploads/images/posts/inter-rapidisimo/3.jpeg', 74),
	('uploads/images/posts/inter-rapidisimo/4.jpeg', 74),
	('uploads/images/posts/inter-rapidisimo/5.jpeg', 74),
	('uploads/images/posts/dj-barber-chop/0.jpeg', 75),
	('uploads/images/posts/dj-barber-chop/1.jpeg', 75),
	('uploads/images/posts/dj-barber-chop/2.jpeg', 75),
	('uploads/images/posts/dj-barber-chop/3.jpeg', 75),
	('uploads/images/posts/dj-barber-chop/4.jpeg', 75),
	('uploads/images/posts/dj-barber-chop/5.jpeg', 75),
	('uploads/images/posts/dj-barber-chop/6.jpeg', 75),
	('uploads/images/posts/dj-barber-chop/7.jpeg', 75),
	('uploads/images/posts/dj-barber-chop/8.jpeg', 75),
	('uploads/images/posts/dj-barber-chop/9.jpeg', 75),
	('uploads/images/posts/envia/0.jpeg', 76),
	('uploads/images/posts/envia/1.jpeg', 76),
	('uploads/images/posts/efecty-servientrega/0.jpeg', 77),
	('uploads/images/posts/bomberos/0.jpeg', 78),
	('uploads/images/posts/bomberos/1.jpeg', 78),
	('uploads/images/posts/bomberos/2.jpeg', 78),
	('uploads/images/posts/bomberos/3.jpeg', 78),
	('uploads/images/posts/bomberos/4.jpeg', 78),
	('uploads/images/posts/floristeria-y-detalles-alejandra/0.jpeg', 79),
	('uploads/images/posts/jabon-todero-multiusos/0.jpeg', 80),
	('uploads/images/posts/jabon-todero-multiusos/1.jpeg', 80),
	('uploads/images/posts/jabon-todero-multiusos/2.jpeg', 80),
	('uploads/images/posts/masajes-tu-negra-sabrosa/0.jpeg', 81),
	('uploads/images/posts/masajes-tu-negra-sabrosa/1.jpeg', 81),
	('uploads/images/posts/masajes-tu-negra-sabrosa/2.jpeg', 81),
	('uploads/images/posts/masajes-tu-negra-sabrosa/3.jpeg', 81),
	('uploads/images/posts/masajes-tu-negra-sabrosa/4.jpeg', 81),
	('uploads/images/posts/masajes-tu-negra-sabrosa/5.jpeg', 81),
	('uploads/images/posts/masajes-tu-negra-sabrosa/6.jpeg', 81),
	('uploads/images/posts/masajes-tu-negra-sabrosa/7.jpeg', 81),
	('uploads/images/posts/masajes-tu-negra-sabrosa/8.jpeg', 81),
	('uploads/images/posts/masajes-tu-negra-sabrosa/9.jpeg', 81),
	('uploads/images/posts/masajes-tu-negra-sabrosa/10.jpeg', 81),
	('uploads/images/posts/se-busca-barista/0.jpeg', 82),
	('uploads/images/posts/cosina/0.jpeg', 83),
	('uploads/images/posts/plataformas-streaming/0.jpeg', 84),
	('uploads/images/posts/fraiche-perfumes-y-esencias/0.jpeg', 85),
	('uploads/images/posts/fraiche-perfumes-y-esencias/1.jpeg', 85),
	('uploads/images/posts/fraiche-perfumes-y-esencias/2.jpeg', 85),
	('uploads/images/posts/fraiche-perfumes-y-esencias/3.jpeg', 85),
	('uploads/images/posts/fraiche-perfumes-y-esencias/4.jpeg', 85),
	('uploads/images/posts/fraiche-perfumes-y-esencias/5.jpeg', 85),
	('uploads/images/posts/fraiche-perfumes-y-esencias/6.jpeg', 85),
	('uploads/images/posts/fraiche-perfumes-y-esencias/7.jpeg', 85),
	('uploads/images/posts/fraiche-perfumes-y-esencias/8.jpeg', 85),
	('uploads/images/posts/fraiche-perfumes-y-esencias/9.jpeg', 85),
	('uploads/images/posts/graiche-perfumes-y-esencias/0.jpeg', 86),
	('uploads/images/posts/graiche-perfumes-y-esencias/1.jpeg', 86),
	('uploads/images/posts/graiche-perfumes-y-esencias/2.jpeg', 86),
	('uploads/images/posts/graiche-perfumes-y-esencias/3.jpeg', 86),
	('uploads/images/posts/graiche-perfumes-y-esencias/4.jpeg', 86),
	('uploads/images/posts/graiche-perfumes-y-esencias/5.jpeg', 86),
	('uploads/images/posts/graiche-perfumes-y-esencias/6.jpeg', 86),
	('uploads/images/posts/graiche-perfumes-y-esencias/7.jpeg', 86),
	('uploads/images/posts/graiche-perfumes-y-esencias/8.jpeg', 86),
	('uploads/images/posts/la-vineria/0.jpeg', 87),
	('uploads/images/posts/la-vineria/1.jpeg', 87),
	('uploads/images/posts/la-vineria/2.jpeg', 87),
	('uploads/images/posts/la-vineria/3.jpeg', 87),
	('uploads/images/posts/panaderia-uraku/0.jpeg', 88),
	('uploads/images/posts/panaderia-uraku/1.jpeg', 88),
	('uploads/images/posts/panaderia-uraku/2.jpeg', 88),
	('uploads/images/posts/panaderia-uraku/3.jpeg', 88),
	('uploads/images/posts/panaderia-uraku/4.jpeg', 88),
	('uploads/images/posts/miss-papa/0.jpeg', 89),
	('uploads/images/posts/cuidadora/0.jpeg', 90),
	('uploads/images/posts/travesias-restaurante-parrilla/0.jpeg', 91),
	('uploads/images/posts/agropecuaria-samy/0.jpeg', 92),
	('uploads/images/posts/agropecuaria-samy/1.jpeg', 92),
	('uploads/images/posts/agropecuaria-samy/2.jpeg', 92),
	('uploads/images/posts/heladeria-la-golosa/0.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/1.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/2.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/3.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/4.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/5.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/6.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/7.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/8.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/9.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/10.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/11.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/12.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/13.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/14.jpeg', 93),
	('uploads/images/posts/heladeria-la-golosa/15.jpeg', 93),
	('uploads/images/posts/siempre-alegre-market-circasia/0.jpeg', 94),
	('uploads/images/posts/siempre-alegre-market-circasia/1.jpeg', 94),
	('uploads/images/posts/siempre-alegre-market-circasia/2.jpeg', 94),
	('uploads/images/posts/siempre-alegre-market-circasia/3.jpeg', 94),
	('uploads/images/posts/siempre-alegre-market-circasia/4.jpeg', 94),
	('uploads/images/posts/siempre-alegre-market-circasia/5.jpeg', 94),
	('uploads/images/posts/siempre-alegre-market-circasia/6.jpeg', 94),
	('uploads/images/posts/siempre-alegre-market-circasia/7.jpeg', 94),
	('uploads/images/posts/venta-cuentas-streaming/0.jpeg', 95),
	('uploads/images/posts/maquilladora-profesional/0.jpeg', 96);

